// ============================================================
// AI 資金流動網絡 — 數據層 / AI Capital Flow Network — Data Layer
// SCHEMA v3 — FINAL: Round 1 + Round 2 deep-research (對抗式驗證)
//            + targeted source fetches. As of 2026-06-05.
// confidence: confirmed (SEC/一手文件) | reported (多源媒體) | estimate (估計/未驗證)
// amount 單位: USD billions
// ============================================================

const DATA = {
  meta: {
    title: "美國 AI 資金流動與系統性風險地圖 / US AI Capital Flow & Systemic Risk Map",
    asOf: "2026-06-05",
    status: "v3 FINAL · 2 輪深研 + 定向補抓",
    disclaimer:
      "研究用途。confirmed=SEC/一手文件、reported=多源媒體、estimate=估計或未經本研究驗證。健康度評分為本研究綜合判斷（信評、CDS、槓桿、對手集中度、折舊缺口、資金缺口），非信評機構評級。",
  },

  categories: {
    "ai-lab":        { zh: "AI 實驗室",       en: "AI Lab",            color: "#e8554e" },
    "hyperscaler":   { zh: "雲端巨頭",        en: "Hyperscaler",       color: "#4e79e8" },
    "chip":          { zh: "晶片/硬體",       en: "Chips / Hardware",  color: "#2eb086" },
    "neocloud":      { zh: "新雲/GPU租賃",    en: "Neocloud / GPU Lease", color: "#e89a3c" },
    "reit":          { zh: "資料中心 REIT",   en: "Data Center REIT",  color: "#9a6fe8" },
    "private-credit":{ zh: "私募信貸/PE",     en: "Private Credit / PE", color: "#d44fb0" },
    "sovereign":     { zh: "主權/超大基金",   en: "Sovereign / Mega Fund", color: "#5fb4d4" },
    "insurer":       { zh: "保險",            en: "Insurance",         color: "#c2b03c" },
    "pension":       { zh: "退休基金",        en: "Pension Fund",      color: "#8a8f3c" },
    "bank":          { zh: "銀行",            en: "Bank",              color: "#6b7280" },
    "spv":           { zh: "SPV/合資/分拆",   en: "SPV / JV / Spin-off", color: "#f0599a" },
    "energy":        { zh: "電力/基建",       en: "Power / Infra",     color: "#49c0b6" },
  },

  flowTypes: {
    equity:    { zh: "股權投資", en: "Equity",              dash: null },
    debt:      { zh: "債務融資", en: "Debt",                dash: "6,3" },
    lease:     { zh: "租賃契約", en: "Lease",               dash: "2,3" },
    purchase:  { zh: "採購承諾", en: "Purchase Commitment", dash: "10,4" },
    revenue:   { zh: "營收回流", en: "Revenue",             dash: null },
    spv:       { zh: "SPV/表外", en: "SPV / Off-B/S",       dash: "1,4" },
    guarantee: { zh: "擔保/追索", en: "Guarantee / Recourse", dash: "8,2,2,2" },
  },

  entities: [
    // ---- AI 實驗室 ----
    { id: "openai", name: "OpenAI", category: "ai-lab",
      health: { score: 30,
        notesZh: "全系統最大「承諾支出 vs 已籌資本」缺口：~$1.4T 算力成本(至2033, HSBC模型) vs 2025 營收 ~$13B；HSBC 估 2030 前缺口 ~$207B。估值 $852B(2026-03)、累計融資 $110B+ 是唯一緩衝。需求端的根源風險",
        notesEn: "Largest committed-spend vs funded-capital mismatch: ~$1.4T compute costs (thru 2033, HSBC) vs ~$13B 2025 revenue; ~$207B funding gap by 2030. $852B valuation / $110B+ raised is the only buffer. The demand-side root risk" } },
    { id: "anthropic", name: "Anthropic", category: "ai-lab",
      health: { score: 55,
        notesZh: "資本充足且成長中：$30B Series G @ $380B(2026-02)；run-rate $14B(2月)→$30B+(4月,毛額;競對備忘錄稱淨額~$22B)→$47B(5月底,報導)。但 TPU 租金是 $36B SPV 唯一主要還款來源",
        notesEn: "Well-capitalized & growing: $30B Series G @ $380B; run-rate $14B(Feb)→$30B+(Apr, gross; ~$22B net per disputed memo)→$47B(late May, reported). But TPU rent is the $36B SPV's primary repayment source" } },

    // ---- 雲端巨頭 ----
    { id: "msft",  name: "Microsoft", category: "hyperscaler",
      health: { score: 85,
        notesZh: "持 OpenAI ~27%（$13B 承諾/$11.8B 已注資；10-Q 確認）；$196.6B 未開始租約＝全研究最大表外數字；9 個月 PP&E 從 $205B 增至 $283B；現金 9 個月減 $16B；OpenAI 重組產生一次性 $5.9B 稀釋利益（非現金）",
        notesEn: "~27% OpenAI ($13B committed/$11.8B funded per 10-Q); $196.6B uncommenced leases = largest off-B/S figure in this study; PP&E $205B→$283B in 9 months; one-time $5.9B OpenAI dilution gain (non-cash)" },
      leverage: {
        totalDebt: 125.4, cash: 78.3, netDebt: 47.1, ebitda: null, debtToEbitda: null,
        ocf: 170.0, capex: 132.8, fcf: 37.2, offBS: 196.6, effectiveLeverage: 1.9,
        period: "10-Q FY26 Q3 (2026-03-31)；OCF/capex 為 9 個月年化",
        citation: "SEC 10-Q msft-20260331 (acc. 0001193125-26-191507)",
        keyRisksZh: ["表內債 $40.3B + 融資租賃 $62.9B + 營業租賃 $22.2B", "$196.6B 未開始租約（FY26-31 起租、最長 21 年）", "現金+短投 $94.6B→$78.3B（9 個月）", "OpenAI 權益法帳面 $6.0B→$11.1B；$5.9B 利益為一次性稀釋利得"] } },
    { id: "googl", name: "Google", category: "hyperscaler",
      health: { score: 82,
        notesZh: "Q1'26 長債 $46.5B→$77.5B；正在變成 neocloud 層的擔保人：$9.0B 財務擔保 + $28.4B 資料中心信用衍生品名目（一季前 $16.9B）+ $33.3B 後續 backstop 框架（4 月已承諾 $15.3B 給某資料中心商）；VIE 出資承諾 $1.1B→$40.7B（$10B+$30B 里程碑、會計上列為股權衍生品，未具名但與 Anthropic 一致）",
        notesEn: "LT debt $46.5B→$77.5B in Q1'26; becoming the neocloud layer's guarantor: $9.0B guarantees + $28.4B DC credit derivatives (vs $16.9B a quarter ago) + $33.3B backstop framework ($15.3B committed Apr); VIE commitments $1.1B→$40.7B ($10B+$30B milestone equity derivative, unnamed but Anthropic-consistent)" },
      leverage: {
        totalDebt: 95.9, cash: 126.8, netDebt: -30.9, ebitda: null, debtToEbitda: null,
        ocf: 183.2, capex: 142.7, fcf: 40.5, offBS: 478.7, effectiveLeverage: 3.1,
        period: "10-Q Q1 2026 (2026-03-31)；OCF/capex 為 Q1 年化",
        citation: "SEC 10-Q goog-20260331 (acc. 0001652044-26-000048)",
        keyRisksZh: ["表外合計 $478.7B：未開始租約 $75.6B + 採購承諾 $332.4B + 擔保 $9.0B + 信用衍生品 $28.4B + backstop 框架 $33.3B", "信用衍生品一季 $16.9B→$28.4B（最長 15 年）——對手未具名", "非上市證券 $68.7B→$106.9B（一季）"] } },
    { id: "amzn",  name: "Amazon", category: "hyperscaler",
      health: { score: 76,
        notesZh: "⚠ 槓桿上升最快的巨頭：債務面值一季 $68.8B→$122.6B（3 月單月發 $37B+€14.5B）；TTM 自由現金流 $25.9B→$1.2B 崩跌；Q1 其他收益 $15.6B 主要來自 Anthropic Level 3 紙上增值（≈營業利益 65%）；折舊 6→5 年（誠實面）；Talen PPA 需求風險自擔",
        notesEn: "⚠ Fastest-levering hyperscaler: debt face $68.8B→$122.6B in one quarter; TTM FCF collapsed $25.9B→$1.2B; Q1 other income $15.6B mostly Level 3 Anthropic markup (≈65% of operating income); depreciation honestly cut 6→5 yrs; bears Talen PPA demand risk" },
      leverage: {
        totalDebt: 227.5, cash: 143.1, netDebt: 84.4, ebitda: null, debtToEbitda: null,
        ocf: 148.5, capex: 147.3, fcf: 1.2, offBS: 210.1, effectiveLeverage: 2.9,
        period: "10-Q Q1 2026 (2026-03-31)；OCF/capex/FCF 為 TTM",
        citation: "SEC 10-Q amzn-20260331 (acc. 0001018724-26-000014)",
        keyRisksZh: ["債務面值 $122.6B + 租賃 $104.9B；利息 Q1 $541M→$800M", "TTM capex $147.3B ≈ TTM OCF $148.5B——自由現金流歸零", "表外：未開始租約 $106.3B（含物流設施）+ 無條件採購義務 $103.8B；合約承諾總額 $569.3B", "Anthropic/OpenAI 持倉 $16.2B→$48.1B（一季），Level 3 增值入損益"] } },
    { id: "meta",  name: "Meta", category: "hyperscaler",
      health: { score: 74,
        notesZh: "10-Q 確認：Hyperion JV 為不併表權益法 VIE（持 20%、非主要受益人）；$28B 殘值擔保門檻「未認列任何負債」；揭露最大損失曝險 $45.99B；表外租約 $182.9B + 採購承諾 $237.7B，4 月再加 ~$24B；Burry 指控 2028 盈餘高估 20.8%",
        notesEn: "10-Q confirms: Hyperion is an UNCONSOLIDATED equity-method VIE (20%, not primary beneficiary); $28B RVG threshold with NO liability recorded; disclosed max exposure $45.99B; $182.9B off-B/S leases + $237.7B purchase commitments, +$24B in April" },
      leverage: {
        totalDebt: 86.7, cash: 81.2, netDebt: 5.5, ebitda: null, debtToEbitda: null,
        ocf: 128.9, capex: 79.4, fcf: 49.5, offBS: 448.6, effectiveLeverage: 4.2,
        period: "10-Q Q1 2026 (2026-03-31)；OCF/capex 為 Q1 年化",
        citation: "SEC 10-Q meta-20260331 (acc. 0001628280-26-028526)",
        keyRisksZh: ["長債 $58.7B + 營業租賃 $28.0B", "表外 $448.6B：未開始租約 $182.9B（至 2036 起租、最長 30 年）+ 採購承諾 $237.7B + RVG $28B（零負債認列）", "Hyperion 最大損失曝險 $45.99B（自揭）", "4 月單月再加 ~$24B 多年期基建合約"] } },
    { id: "orcl",  name: "Oracle", category: "hyperscaler",
      health: { score: 42,
        notesZh: "Q3 FY26 (2026-02-28)：RPO $553B（年增 325%）；借款 ~$134.6B vs 現金 $38.5B（3.5 倍）；TTM 自由現金流 -$24.7B（capex $48.3B ≈ OCF 的 2 倍）；CDS 151.3bps 創 2009 以來新高；S&P/Moody's 展望負向。OpenAI 風險進入公開債市的最大管道",
        notesEn: "Q3 FY26: RPO $553B (+325% YoY); borrowings ~$134.6B vs cash $38.5B; TTM FCF -$24.7B (capex ~2x OCF); CDS highest since 2009; negative outlooks. Largest channel from OpenAI risk into public bond markets" },
      leverage: {
        totalDebt: 134.6, cash: 38.5, netDebt: 96.1, ebitda: null, debtToEbitda: null,
        ocf: 23.5, capex: 48.25, fcf: -24.7, offBS: null, effectiveLeverage: 5.7,
        period: "Q3 FY2026 (2026-02-28) 8-K 財報；OCF/capex/FCF 為 TTM；FY26 10-K 約 7 月才發布",
        citation: "Oracle Q3 FY26 earnings 8-K Ex.99.1 (2026-03-10)",
        keyRisksZh: ["TTM FCF -$24.7B——巨頭中唯一深度負值", "RPO $553B 年增 325%，集中於 OpenAI——backlog 是承諾不是現金", "借款 $134.6B、現金 $38.5B", "FY26 全年 capex 指引 ~$50B；表外未開始租約本輪未取得"] } },

    // ---- 晶片/硬體 ----
    { id: "nvda", name: "Nvidia", category: "chip",
      health: { score: 78,
        notesZh: "資產負債表無懈可擊（債 $8.5B vs 季 OCF $50B），但盈餘品質與集中度惡化：單季 $18.6B 投入私人 AI 股權（=OCF 37%）、非上市投組 15 個月 12.5 倍（$3.4B→$42.3B）+$27B 待投；單季 $15.9B 股權利得入損益；前三大客戶 54% 營收、單一客戶應收 ~$12B；10-K/10-Q 連三季原文：「一家 AI 研究與部署公司透過向我們的客戶購買雲服務、間接貢獻可觀營收」",
        notesEn: "Pristine B/S (debt $8.5B vs $50B/qtr OCF) but earnings quality & concentration deteriorating: $18.6B/qtr into private AI equity (37% of OCF), non-marketable portfolio 12.5x in 15 months (+$27B committed); $15.9B/qtr equity gains in P&L; top-3 customers = 54% of revenue, one owes ~$12B AR; three consecutive filings: 'one AI research and deployment company contributed meaningful revenue indirectly'" },
      leverage: {
        totalDebt: 8.5, cash: 80.6, netDebt: -72.1, ebitda: null, debtToEbitda: null,
        ocf: 201.4, capex: 7.0, fcf: 194.4, offBS: 185.5, effectiveLeverage: 1.0,
        period: "10-K FY2026 (2026-01-25) + 10-Q Q1 FY2027 (2026-04-26)；OCF/capex 為 Q1 年化",
        citation: "SEC 10-K nvda-20260125 + 10-Q nvda-20260426（XBRL 交叉驗證）",
        keyRisksZh: ["表外/遠期合計 ~$185.5B：供應承諾 $119B（半年翻倍）+ 雲服務協議 $30B（CoreWeave 式回購所在科目）+ 投資承諾 $27B + 廠商 $6B + 資料中心租約擔保 $3.5B（押金僅 $712M）", "單季 $18.6B 買私人股權＝拿 37% 營運現金流回灌自己的客戶生態系", "$15.9B 單季股權利得（大多未實現；$27.4B 短期鎖倉+$8.9B 鎖至 2027/12）", "AR 集中：30%/18%/16%——單一匿名客戶欠 ~$12B"] } },
    { id: "amd", name: "AMD", category: "chip",
      health: { score: 72,
        notesZh: "OpenAI 6GW 標題中僅 1GW 有約束力（8-K）；Q1'26 10-Q 確認發了兩份 160M 股 penny warrant（OpenAI 2025-10 + Meta 2026-02, $0.01 行使價），解鎖含「透過授權第三方間接採購」——經雲端中介的採購也算；尚未有股份 vest、暫列負債",
        notesEn: "Only 1 of 6 GW binding; Q1'26 10-Q confirms TWO 160M-share penny warrants (OpenAI Oct-25 + Meta Feb-26), vesting incl. purchases 'indirectly through authorized third parties'; none vested yet, liability-classified" } },
    { id: "avgo", name: "Broadcom", category: "chip",
      health: { score: 68,
        notesZh: "AI 半導體營收 Q2 FY26 $10.8B（+143%）、Q3 指引 $16B；8-K (2026-04-06)：與 Google 簽 TPU 長約+供應保證至 2031、Anthropic 自 2027「透過 Broadcom」取得 ~3.5GW、消耗「取決於 Anthropic 持續商業成功」、融資「洽談中」；⚠ 殘值擔保經全市場 EDGAR 驗證零揭露（Broadcom 全體系僅一個申報主體、無子公司可藏；ASC 460 下擔保一經簽發必須入合併報表）——成交前是揭露真空、成交後 Q2 10-Q 必須現形",
        notesEn: "AI semis $10.8B (+143%), $16B Q3 guide; 8-K (2026-04-06): Google TPU LTA + supply assurance thru 2031, Anthropic accesses ~3.5GW 'through Broadcom' from 2027, consumption 'dependent on Anthropic's continued commercial success', financing 'in discussions'; ⚠ RVG verified ZERO disclosure market-wide on EDGAR (Broadcom has exactly ONE SEC registrant — no subsidiary to hide in; ASC 460 forces consolidated disclosure once issued)" },
      leverage: {
        totalDebt: 64.9, cash: 19.6, netDebt: 45.3, ebitda: null, debtToEbitda: null,
        ocf: 42.0, capex: 0.9, fcf: 41.0, offBS: 4.3, effectiveLeverage: 1.6,
        period: "Q2 FY2026 8-K (2026-05-03) + Q1 FY2026 10-Q；OCF/FCF 為 Q2 年化",
        citation: "SEC 8-K avgo-05032026 + Q1 10-Q；RVG 搜尋為負面發現",
        keyRisksZh: ["債務 $64.9B（VMware 遺留）持平、AI 成長全靠 OCF 自籌", "報導中的 ~$31B TPU 殘值擔保未出現在任何文件——或有負債的揭露真空", "Q2 FY26 10-Q（~6 月中）是下一個可能現形的地方"] } },

    // ---- 新雲 ----
    { id: "coreweave", name: "CoreWeave", category: "neocloud",
      health: { score: 15,
        notesZh: "⚠ 最薄弱環節（SEC 文件逐行確認）：債務 15 個月 3 倍（$8.0B→$21.6B→$25.1B，Q1'26 後再加 $9.9B）；FY25 償債 $4.4B＞OCF $3.1B；利息年化 $1.55B≈營收 25%；現金 $2.2B vs 2026 年內到期 $6.1B；Microsoft 佔營收 67%；表外租約 $40.7B+；除 DDTL 4.0 外全部設施由母公司無條件擔保",
        notesEn: "⚠ Weakest link (filing-verified): debt 3x in 15 months ($8.0B→$21.6B→$25.1B, +$9.9B post-Q1); FY25 debt service $4.4B > OCF $3.1B; interest ~25% of revenue; cash $2.2B vs $6.1B due within 2026; Microsoft = 67% of revenue; $40.7B+ off-B/S leases; all DDTLs except 4.0 unconditionally parent-guaranteed" },
      leverage: {
        totalDebt: 25.1, cash: 2.2, netDebt: 22.9, ebitda: 3.1, debtToEbitda: 6.9,
        ocf: 3.0, capex: 10.3, fcf: -7.25, offBS: 50.0, effectiveLeverage: 24.2,
        period: "10-K FY2025 + 10-Q 2026-03-31（Q1 後另有 $4B 可轉債+$2.8B 9.75% 債+$3.1B DDTL 5.0）",
        citation: "SEC: crwv-20251231 (10-K), crwv-20260331 (10-Q), 4Q25 earnings 8-K",
        keyRisksZh: [
          "FY25 償債 $4.4B > 營運現金流 $3.1B",
          "Capex = OCF 的 2.6-3.4×，全靠新債+增資餵養",
          "債務/調整後EBITDA 6.9×（含營業租賃 9.6×；含表外總索賠 ~$75-90B vs EBITDA $3.1B ≈ 24×+）",
          "DDTL 實際利率 7-15%；9.75% 高息債",
          "到期牆：2026 剩餘 $6.1B、2027 $5.7B vs 現金 $2.2B",
          "RPO $98.8B 僅 36% 在 24 個月內認列——抵押品是長天期承諾",
          "受限現金瀑布：先償債、後放款給公司",
          "GPU 資產 $33.9B 僅折舊 $3.4B——年輕未經考驗的資產基礎"
        ] } },
    { id: "cohere", name: "Cohere", category: "ai-lab",
      health: { score: 35,
        notesZh: "DDTL 5.0 兩家抵押信用之一。財務體質（2026-02 投資人備忘錄, CNBC/BetaKit）：ARR $240M（2024 底 $62M → +287%，季增 >50%）、毛利 ~70%、85% 來自企業私有部署（Oracle/Fujitsu/RBC/LG）；估值 $7B、歷史總募資僅 ~$1.54B；獲利目標 2029（=持續燒錢）；投資人含 Nvidia、AMD Ventures、PSP（加拿大退休金）。⚠ 規模與 OpenAI 差兩個數量級，卻共同支撐 $3.1B 公開交易 GPU 債",
        notesEn: "One of DDTL 5.0's two collateral credits. Financials (Feb-26 investor memo): ARR $240M (+287% YoY from $62M), ~70% GM, 85% enterprise private deployments; $7B valuation, only ~$1.54B ever raised; profitability targeted 2029 (= burning until then); investors include Nvidia, AMD Ventures, PSP (Canadian pension). ⚠ Two orders of magnitude smaller than OpenAI, yet co-supporting $3.1B of publicly traded GPU debt" },
      leverage: {
        totalDebt: null, cash: null, netDebt: null, ebitda: null, debtToEbitda: null,
        ocf: 0.24, capex: null, fcf: null, offBS: null, effectiveLeverage: null,
        period: "投資人備忘錄 (2026-02, CNBC/BetaKit 轉述)；私人公司無申報；ocf 欄位放 ARR $240M 作參考",
        citation: "CNBC (2026-02-13) + BetaKit；募資: cohere.com (2025-08 $500M @ $6.8B) + BetaKit (2025-09 +$100M @ $7B)",
        keyRisksZh: ["CoreWeave 合約金額未揭露（信貸協議中以[*]刪節、schedule 未附）", "⚠ 交叉違約：信貸協議下 Cohere 的 MSA 若被全面終止＝整個 $3.1B 設施的違約事件——它不是池子裡的一小塊，是同等引爆器", "歷史總募資 $1.54B、獲利要等 2029：付租金靠募資+成長", "Nvidia/AMD 既是投資人又是其算力的最終供應商——循環再現"] } },
    { id: "crusoe", name: "Crusoe", category: "neocloud",
      health: { score: 45, notesZh: "Stargate Abilene 建設方/JV 共同發起人；2026-03 約 600MW 擴建計畫取消、Microsoft 接收相鄰產能——需求軟化首個實體訊號", notesEn: "Abilene builder/JV co-sponsor; ~600MW expansion scrapped Mar 2026, Microsoft took adjacent capacity — first physical demand-softening signal" } },

    // ---- SPV / JV ----
    { id: "cw-spv8", name: "CW SPV VIII (DDTL 4.0)", category: "spv",
      health: { score: 50,
        notesZh: "$8.5B、首例投資級 GPU 抵押融資（A3/A-low, SOFR+225）；無追索但含 bad-boy 擔保；抵押＝SPV 全資產+客戶合約+資料中心租約三層；advance rate 建設期 90% LTC、穩定後 1.2x DSCR ⇒ 可達 ~102% LTC——債可超過資產成本",
        notesEn: "$8.5B, first IG GPU-backed (A3/A-low); non-recourse but bad-boy guarantee; collateral = SPV assets + customer contract + DC leases; 90% LTC in construction, 1.2x DSCR post-stabilization ⇒ up to ~102% LTC — debt can exceed asset cost" } },
    { id: "cw-spv5", name: "CW DDTL V SPV (5.0)", category: "spv",
      health: { score: 20,
        notesZh: "$3.1B 垃圾級(Ba2/BB+) SOFR+450；兩家客戶＝OpenAI + Cohere（銀團報導）。信貸協議（ex10.1, 101 處[*]刪節）顯示兩份 MSA 交叉抵押進同一池、無分層：單一放貸公式 71.42%×capex（隱含總建置 ~$4.34B、股權墊 28.6%）；任一 MSA 重大違約→全設施 Cash Trap；任一 MSA 全面終止→整個 $3.1B 的違約事件——最弱信用（Cohere）持有與 OpenAI 同等的引爆權；唯一不對稱：其中一份 MSA 的附屬基建認列有[*]上限。可公開交易但抵押池組成被刪節——買方看得到價格、看不到池子",
        notesEn: "$3.1B junk; customers = OpenAI + Cohere. Credit agreement (ex10.1, 101 redactions) shows the two MSAs are CROSS-COLLATERALIZED into one pool, no tranching: single 71.42%-of-capex advance formula (implies ~$4.34B total build); material breach of EITHER MSA → facility-wide Cash Trap; full termination of EITHER MSA → Event of Default on the whole $3.1B — the weakest credit (Cohere) holds the same detonator as OpenAI; only asymmetry: one MSA's ancillary-infra attribution is capped at [*]. Publicly tradeable, but the pool composition is redacted" } },
    { id: "anthropic-tpu-spv", name: "Anthropic TPU SPV", category: "spv",
      health: { score: 35,
        notesZh: "~$36B（Burry 5/29 文中 $38B）：$6B A1 + $25B A2(~5.75%) + $4.5B B；6/5 仍在銷售未 close；B 段為無增強損失層；Broadcom RVG 承接 senior 尾部風險",
        notesEn: "~$36B (Burry's '$38B'): $6B A1 + $25B A2 (~5.75%) + $4.5B B; not closed as of Jun 5; B tranche is the unenhanced loss piece; Broadcom RVG absorbs senior tail" } },
    { id: "beignet", name: "Beignet LLC (Hyperion JV)", category: "spv",
      health: { score: 60,
        notesZh: "Blue Owl 80%/Meta 20%；~$27.3B A+ 債（PIMCO 錨定 ~$18B）+~$2.5B 股權；Meta 售後回租+$28B 殘值擔保（未列或有負債）",
        notesEn: "Blue Owl 80%/Meta 20%; ~$27.3B A+ notes (PIMCO ~$18B) + ~$2.5B equity; Meta leaseback + $28B RVG (unreported contingent liability)" } },
    { id: "stargate", name: "Stargate JV", category: "spv",
      health: { score: 40,
        notesZh: "宣示 $500B；股權比例（OpenAI/SoftBank/Oracle/MGX）與已部署資本未公開——兩輪深研皆無法驗證，本身就是不透明度的證據",
        notesEn: "Announced $500B; equity split & deployed capital undisclosed — survived neither research round; the opacity is itself a finding" } },
    { id: "abilene", name: "Stargate Abilene JV", category: "spv",
      health: { score: 50,
        notesZh: "旗艦 1.2GW 園區：Crusoe/Blue Owl 實物資產/Primary Digital $15B JV（股權比例未公開）；JPMorgan ~$9.6B 貸款（含 $7.1B 建設段）；Oracle 營運、OpenAI 使用",
        notesEn: "Flagship 1.2GW campus: $15B Crusoe/Blue Owl Real Assets/Primary Digital JV (splits undisclosed); ~$9.6B JPMorgan loans (incl. $7.1B construction); Oracle operates for OpenAI" } },

    // ---- REIT / 電力 ----
    { id: "qts", name: "QTS (Blackstone)", category: "reit",
      health: { score: 55,
        notesZh: "Blackstone 2021 年 ~$10B 收購後擴張 8 倍、3GW+；重度證券化：$3.46B CMBS(2025-11)+$1.5B(2025-07)；資料中心 ABS/CMBS H1'25 $13.4B（年增一倍）、佔 SASB 市場 13%",
        notesEn: "8x expansion since Blackstone's ~$10B 2021 take-private, 3GW+; heavily securitized: $3.46B CMBS (Nov-25) + $1.5B (Jul-25); DC ABS/CMBS $13.4B H1'25 (2x YoY), 13% of SASB market" } },
    { id: "talen", name: "Talen Energy", category: "energy",
      health: { score: 62,
        notesZh: "Susquehanna 核電 1,920MW PPA 供 AWS 至 2042（~$18B 估）；長約「顯著降低 Talen 市場風險」＝需求風險轉移給 Amazon；2026-04 發 $4B 新債、贖回 $1.2B 高息債",
        notesEn: "1,920MW nuclear PPA to AWS thru 2042; demand risk transferred to Amazon; Apr-26: $4B new notes, redeemed $1.2B high-cost debt" },
      leverage: {
        totalDebt: 6.78, cash: 1.03, netDebt: 5.75, ebitda: 1.9, debtToEbitda: 3.0,
        ocf: null, capex: null, fcf: null, offBS: null, effectiveLeverage: 3.6,
        period: "10-Q Q1 2026 (2026-03-31)；EBITDA 為 2026 指引中值 $1.75-2.05B",
        citation: "Talen Q1 2026 10-Q/8-K（tln-20260331）",
        keyRisksZh: ["淨槓桿 ~3.0×（目標 <3.5×）——AI 鏈中相對健康", "2026-04 再發 $4B 債（Cornerstone 收購）", "現金流命脈已綁定單一買家（AWS）至 2042"] } },

    // ---- 私募信貸 / PE / 主權 ----
    { id: "apollo", name: "Apollo / Athene", category: "private-credit",
      health: { score: 58, notesZh: "保險浮存金（Athene）支撐 AI 信貸；共同結構 Anthropic TPU SPV；Athene 對 AI 信貸的確切組合占比未揭露", notesEn: "Athene float backs AI credit; co-structuring Anthropic TPU SPV; Athene's exact AI-credit portfolio share undisclosed" } },
    { id: "blackstone", name: "Blackstone (BXCI)", category: "private-credit",
      health: { score: 62, notesZh: "錨定 CW DDTL 4.0（攜保險資金）；共構 Anthropic TPU SPV；旗下 QTS 重度證券化", notesEn: "Anchored CW DDTL 4.0 (with insurance capital); co-structuring Anthropic TPU SPV; owns heavily-securitized QTS" } },
    { id: "blueowl", name: "Blue Owl", category: "private-credit",
      health: { score: 55, notesZh: "Hyperion JV 80% + Abilene JV 發起人 + $7B 數位基建基金（NY/PA 退休金為 LP）——單一管理人橫跨三大結構", notesEn: "80% of Hyperion + Abilene JV sponsor + $7B digital infra fund (NY/PA pensions as LPs) — one manager across three structures" } },
    { id: "pimco", name: "PIMCO", category: "private-credit",
      health: { score: 65, notesZh: "Hyperion 債券錨定買家 ~$18B（144A）——退休帳戶與保險資金的下游管道", notesEn: "Hyperion notes anchor ~$18B (144A) — downstream conduit for retirement & insurance money" } },
    { id: "softbank", name: "SoftBank", category: "sovereign",
      health: { score: 38,
        notesZh: "對 OpenAI 承諾 $64.6B（~13%）；總債務 ~$135B；為籌資賣 Nvidia($5.83B)+T-Mobile($12.73B)、$40B 過橋貸款、再疊 $10B 保證金貸款（抵押品=OpenAI 股權, SOFR+425）；S&P BB+ 展望負向、CDS ~360bps、兩年缺口 $32B。OpenAI 估值的槓桿化單邊押注",
        notesEn: "$64.6B committed to OpenAI (~13%); ~$135B total debt; sold Nvidia ($5.83B) + T-Mobile ($12.73B), $40B bridge + margin loan collateralized BY the OpenAI stake; S&P BB+ negative, CDS ~360bps. A leveraged one-way bet on OpenAI's valuation" },
      leverage: {
        totalDebt: 135.0, cash: null, netDebt: 55.0, ebitda: null, debtToEbitda: null,
        ocf: null, capex: null, fcf: null, offBS: null, effectiveLeverage: null,
        period: "FY2025 (2026-03-31) 官方 SOTP/財報；非 SEC（東京上市）",
        citation: "group.softbank SOTP: NAV ¥40.06T、淨債 ¥8.21T、LTV 17.0%（公司自報口徑）；總債 ~$135B 為合併口徑 (TNW)",
        keyRisksZh: ["公司自報 LTV 17.0% vs 合併總債 ~$135B——口徑差異巨大（LTV 排除部分資產擔保融資）", "OpenAI 持股在官方 SOTP 中不單列（藏於 SVF2 ¥17.19T / Others ¥4.61T）——NAV 最大單一不透明項", "2026-05-08：保證金貸款目標從 $10B 砍 40% 至 $6B（Bloomberg）——市場胃納不足的直接證據"] } },
    { id: "mgx", name: "MGX (Abu Dhabi)", category: "sovereign",
      health: { score: 72, notesZh: "Anthropic Series G 共同領投（額度未拆分）；Stargate 股東；對 OpenAI 確切支票額未公開", notesEn: "Anthropic Series G co-lead (allocation undisclosed); Stargate shareholder; OpenAI check size undisclosed" } },
    { id: "gic", name: "GIC / Coatue 等機構", category: "sovereign",
      health: { score: 75, notesZh: "Anthropic $30B Series G 領投（GIC+Coatue, 含 D.E. Shaw/Dragoneer/Founders Fund/ICONIQ/MGX）", notesEn: "Led Anthropic's $30B Series G (GIC+Coatue, with DESV/Dragoneer/FF/ICONIQ/MGX)" } },

    // ---- 終端 ----
    { id: "banks", name: "銀行體系 Banks (JPM/MS/MUFG/GS)", category: "bank",
      health: { score: 70,
        notesZh: "CW 融資結構/主辦行；Abilene $9.6B 貸款；Meta $30B 債承銷；對私募信貸基金授信 ~$220B（FSB）",
        notesEn: "CW facility arrangers; $9.6B Abilene loans; Meta $30B underwriting; ~$220B credit lines to private credit funds (FSB)" } },
    { id: "insurers", name: "壽險業 Life Insurers", category: "insurer",
      health: { score: 60, notesZh: "投資組合 ~10% 在私募信貸（FSB）；直接參與 CW DDTL 4.0；PE 系保險（Athene/Global Atlantic）確切金額未揭露", notesEn: "~10% of portfolios in private credit (FSB); directly in CW DDTL 4.0; PE-owned insurer dollar amounts undisclosed" } },
    { id: "pensions", name: "美國退休基金 US Pensions", category: "pension",
      health: { score: 66,
        notesZh: "持有私募信貸基金 ~31% 資產（Fed via FSB）；NY/PA 州退休金在 Blue Owl $7B 基金——傳染鏈終點＝一般人的退休金",
        notesEn: "~31% of private credit fund assets (Fed via FSB); NY/PA state plans in Blue Owl's $7B fund — terminal node = ordinary people's retirement money" } },
  ],

  flows: [
    // ======== OpenAI 需求側承諾堆疊 ========
    { source: "openai", target: "msft", type: "purchase", amount: 250,
      date: "2025-10-28", confidence: "confirmed",
      citation: "Microsoft 8-K (SEC, msft-ex99_2): OpenAI contracted to purchase an incremental $250B of Azure services",
      noteZh: "$250B Azure 增量採購承諾（同一 8-K 揭露微軟持股 ~27%/$135B、放棄 ROFR）",
      noteEn: "$250B incremental Azure commitment (same 8-K discloses ~27%/$135B stake, dropped ROFR)" },
    { source: "msft", target: "openai", type: "equity", amount: 13,
      date: "2023-2026", confidence: "confirmed",
      citation: "Microsoft 10-Q FY26Q3：承諾 $13B/已注資 $11.8B、持股 ~27%（HLBV 權益法）；2025-10 OpenAI 重組產生一次性 $5.9B 稀釋利益（9 個月、稅後 +$4.48B 淨利 ≈ EPS $0.60）",
      noteZh: "$13B 承諾（$11.8B 已注資）→ ~27%；重組稀釋利益 $5.9B 為一次性非現金",
      noteEn: "$13B committed ($11.8B funded) → ~27%; the $5.9B recap dilution gain is one-time, non-cash" },
    { source: "openai", target: "amzn", type: "purchase", amount: 38,
      date: "2025-11-03", confidence: "confirmed",
      citation: "OpenAI + AWS 雙方一手新聞稿：7 年 $38B（數十萬顆 GB200/GB300）",
      noteZh: "AWS 7 年 $38B 算力協議", noteEn: "7-yr $38B AWS compute arrangement" },
    { source: "openai", target: "orcl", type: "purchase", amount: 300,
      date: "2025-09", confidence: "reported",
      citation: "Moody's via Reuters (2025-09-17) + Senate FSOC letter",
      noteZh: "Oracle $300B AI 合約（OpenAI 為主）——HSBC 模型總承諾 ~$1.4T 的最大單筆",
      noteEn: "Oracle's $300B AI contracts (mostly OpenAI) — largest single piece of the ~$1.4T stack" },
    { source: "meta", target: "coreweave", type: "purchase", amount: 21,
      date: "2026-03", confidence: "confirmed",
      citation: "CoreWeave Q1'26 earnings 8-K (2026-05-07): 3 月與 Meta 簽新 $21B 承諾（在原 ~$14.2B 之上）；backlog 增至 $99.4B",
      noteZh: "Meta 3 月再簽 $21B——CoreWeave 對 Meta 依賴度進一步上升",
      noteEn: "Meta signed a NEW $21B commitment in March — CoreWeave's Meta dependence deepens further" },
    { source: "anthropic", target: "coreweave", type: "purchase", amount: 6.8,
      date: "2026-04-10", confidence: "estimate",
      citation: "CoreWeave Q1'26 8-K 確認協議存在但未揭露金額；$6.8B 數字僅來自單一聚合媒體（MarketMinute/FinancialContent, 2026-04-10, 自註「第三方內容未經驗證」）——以 estimate 標記",
      noteZh: "Anthropic 多年期協議（金額 $6.8B 為弱來源估計）；此合約不在 DDTL 5.0 抵押池內",
      noteEn: "Anthropic multi-year agreement ($6.8B from a single weak source); NOT in the DDTL 5.0 collateral pool" },
    { source: "cohere", target: "coreweave", type: "purchase", amount: 0,
      date: "2026", confidence: "reported",
      citation: "Bloomberg 銀團報導 + PitchBook LCD (2026-04/05): DDTL 5.0 募資購置的 GPU 部署給 OpenAI 與 Cohere（合約金額未揭露）",
      noteZh: "Cohere 合約＝DDTL 5.0 抵押現金流的一半來源（金額未揭露）",
      noteEn: "Cohere's contract = half the DDTL 5.0 collateral cash flow (amount undisclosed)" },
    { source: "openai", target: "coreweave", type: "purchase", amount: 22.4,
      date: "2025", confidence: "confirmed",
      citation: "Senate letter + CoreWeave 揭露: $11.9B(3月)+~$4B(5月)+至$6.5B(9月)",
      noteZh: "OpenAI → CoreWeave 算力採購累計 ~$22.4B", noteEn: "Cumulative ~$22.4B compute commitments" },
    { source: "openai", target: "amd", type: "purchase", amount: 20,
      date: "2025-10-06", confidence: "estimate",
      citation: "AMD 8-K + IR: 6GW 標題中僅首 1GW MI450 有約束力（2H26 部署）；金額為估計（AMD CFO 稱數百億美元級營收）",
      noteZh: "1GW 有約束力採購（6GW 為上限）；金額估計",
      noteEn: "1 GW binding (6 GW ceiling); amount estimated ('tens of billions' per AMD CFO)" },
    { source: "amd", target: "openai", type: "equity", amount: 25,
      date: "2025-10-05", confidence: "confirmed",
      citation: "AMD 8-K (SEC): 160M 股認股權證 @ $0.01、~10% 股本、2030/10/5 到期；解鎖綁部署里程碑+股價目標(至$600)；價值隨股價變動（此處以名目估計呈現）",
      noteZh: "160M 股權證（~10% AMD）——循環供應商激勵；金額為名目估計",
      noteEn: "160M-share warrant (~10% of AMD) — circular vendor incentive; notional estimate" },
    { source: "nvda", target: "openai", type: "equity", amount: 30,
      date: "2026-02", confidence: "reported",
      citation: "TechCrunch (2026-03-04): $100B 承諾(2025-09)實際僅 $30B；Q3 FY26 10-Q 確認簽有 OpenAI 投資意向書（LOI）；單季非上市股權現金投入 $18.6B（10-Q 現金流量表）",
      noteZh: "Nvidia 實投 $30B（承諾 $100B 的 30%）後宣布撤退；LOI 經 10-Q 確認",
      noteEn: "Deployed $30B of the $100B pledge, then retreated; the LOI itself is 10-Q-confirmed" },
    { source: "softbank", target: "openai", type: "equity", amount: 64.6,
      date: "2025-12 / 2026", confidence: "reported",
      citation: "TNW (2026-04-23): $40-41B 已完成(2025-12) + $30B 待 close = $64.6B 取得 ~13%",
      noteZh: "SoftBank 累計承諾 $64.6B（~13%）——用賣資產+過橋+保證金貸款拼出來的",
      noteEn: "SoftBank's $64.6B (~13%) — funded by asset sales + bridge + margin loan" },
    { source: "banks", target: "softbank", type: "debt", amount: 10,
      date: "2026-04", confidence: "reported",
      citation: "TNW (2026-04-23): $10B 保證金貸款、SOFR+425(~7.88%)、2+1 年、抵押品=OpenAI 持股；疊在 $40B 過橋之上；公布後 CDS +10bps 至 ~360",
      noteZh: "保證金貸款：抵押品是 OpenAI 股權本身——估值即抵押品價值",
      noteEn: "Margin loan collateralized by the OpenAI stake itself — the valuation IS the collateral" },

    // ======== Anthropic 供給側 ========
    { source: "gic", target: "anthropic", type: "equity", amount: 30,
      date: "2026-02-12", confidence: "confirmed",
      citation: "Anthropic 一手新聞稿 + GIC 官網: $30B Series G @ $380B post（GIC/Coatue 領投, MGX 等共同領投）",
      noteZh: "Series G $30B @ $380B；同稿揭露 run-rate $14B、連三年 >10x",
      noteEn: "$30B Series G @ $380B; same release: $14B run-rate, >10x annually for 3 yrs" },
    { source: "amzn", target: "anthropic", type: "equity", amount: 13,
      date: "2026-04-20", confidence: "confirmed",
      citation: "Amazon 10-Q Q1'26 Note 2: $8.0B 可轉債（2023 Q3-2025 Q4）+ 期後 $5.0B 無表決權特別股；另有 $5B 後續輪選擇權",
      noteZh: "已投 ~$13B；持倉帳面值一季 $16.2B→$48.1B（Level 3 增值入損益）",
      noteEn: "~$13B invested; carrying value $16.2B→$48.1B in one quarter (Level 3 markups through P&L)" },
    { source: "amzn", target: "anthropic", type: "debt", amount: 20,
      date: "2026-04", confidence: "confirmed",
      citation: "Amazon 10-Q Q1'26 Note 2: 至 $20B 融資額度，可用額度隨 Amazon「交付算力里程碑」解鎖（含 AWS 晶片性能合約義務）；提取以 Anthropic 可轉債/普通股形式",
      noteZh: "⚠ 循環設計：Amazon 交付算力 → 解鎖 Amazon 借錢給 Anthropic → Anthropic 付 AWS 算力費",
      noteEn: "⚠ Circular by design: Amazon delivers compute → unlocks Amazon lending to Anthropic → Anthropic pays AWS" },
    { source: "googl", target: "anthropic", type: "equity", amount: 10,
      date: "2026-04-24", confidence: "confirmed",
      citation: "Alphabet 10-Q Q1'26 VIE 註記：未具名「未來私人投資」$10B 資本承諾 + $30B 里程碑出資（至 2030）、會計列為 Level 3 股權衍生品；VIE 承諾 $1.1B→$40.7B；對手與 Anthropic 報導一致（Bloomberg 2026-04）",
      noteZh: "$10B 前置（Q2'26 撥付）+ $30B 里程碑——10-Q 以股權衍生品揭露",
      noteEn: "$10B upfront (funding Q2'26) + $30B milestone — disclosed in 10-Q as an equity derivative" },
    { source: "nvda", target: "anthropic", type: "equity", amount: 10,
      date: "2025-11", confidence: "confirmed",
      citation: "Nvidia Q3 FY26 10-Q 原文：「2025 年 11 月簽訂協議（附成交條件）投資 Anthropic 至 $10B」（XBRL tag: AnthropicPBCMember）",
      noteZh: "Nvidia 至 $10B（10-Q 確認；後續關係惡化、黃仁勳稱可能是最後一輪）",
      noteEn: "Up to $10B (10-Q confirmed; relationship later soured, Huang: likely 'its last')" },

    // ======== Anthropic TPU SPV（Burry 的 $38B）========
    { source: "apollo", target: "anthropic-tpu-spv", type: "debt", amount: 18,
      date: "2026-05", confidence: "reported",
      citation: "Bloomberg (2026-05-28) / PE Wire / PitchBook: Apollo+Blackstone 共構 ~$36B（平均拆分顯示）",
      noteZh: "~$36B 結構：$6B A1 + $25B A2(~5.75%) + $4.5B B；6/5 仍在銷售",
      noteEn: "~$36B: $6B A1 + $25B A2 (~5.75%) + $4.5B B; in syndication as of Jun 5" },
    { source: "blackstone", target: "anthropic-tpu-spv", type: "debt", amount: 18,
      date: "2026-05", confidence: "reported",
      citation: "Bloomberg (2026-05-28): Burry 5/29 引用數字為 $38B；是否已 close 兩輪深研皆未能確認",
      noteZh: "共同結構方；close 與否未確認", noteEn: "Co-structuring; closing unconfirmed" },
    { source: "anthropic-tpu-spv", target: "googl", type: "purchase", amount: 36,
      date: "2026", confidence: "reported",
      citation: "PE Wire: SPV 募資購買 Google TPU",
      noteZh: "SPV 買 TPU——Google 立即變現、硬體風險出表",
      noteEn: "SPV buys TPUs — Google monetizes instantly, hardware off its books" },
    { source: "anthropic-tpu-spv", target: "anthropic", type: "lease", amount: 36,
      date: "2026", confidence: "reported",
      citation: "PE Wire/Bloomberg: 長期租約；Anthropic 租金為主要還款來源",
      noteZh: "Anthropic 租金＝SPV 債務唯一主要還款來源（~1GW TPU）",
      noteEn: "Anthropic's rent is the debt's primary repayment source (~1GW TPUs)" },
    { source: "avgo", target: "anthropic-tpu-spv", type: "guarantee", amount: 31,
      date: "2026-06-02", confidence: "reported",
      citation: "Bloomberg (2026-06-02): Broadcom RVG 壓低 A2 至 ~5.75%；⚠ 全市場 EDGAR 全文搜尋驗證（2026-06-05）：無任何 SEC 申報者揭露此擔保；Broadcom 4/6 8-K 確認商業框架（3.5GW 透過 Broadcom）但無 RVG 字樣、融資仍在洽談",
      noteZh: "Broadcom 殘值擔保——目前只活在報導裡、任何資產負債表上都看不到；成交後依 ASC 460 必須入 Broadcom 合併報表（全體系僅一個 SEC 申報主體、無子公司可藏）",
      noteEn: "Broadcom's RVG — exists only in press so far, invisible on every balance sheet; once issued, ASC 460 forces it into Broadcom Inc.'s consolidated disclosures (sole SEC registrant — no subsidiary to hide in)" },

    // ======== CoreWeave 債務堆疊 ========
    { source: "blackstone", target: "cw-spv8", type: "debt", amount: 8.5,
      date: "2026-03-31", confidence: "confirmed",
      citation: "CoreWeave 8-K Ex.99.1 (SEC): BXCI 錨定 + 保險投資人 + 資管；A3/A-low、SOFR+225、無追索權",
      noteZh: "DDTL 4.0：首例投資級 GPU 抵押融資——但評級靠 Meta 合約現金流",
      noteEn: "DDTL 4.0: first IG GPU-backed — but the rating leans on the Meta contract" },
    { source: "cw-spv8", target: "coreweave", type: "spv", amount: 8.5,
      date: "2026-03", confidence: "confirmed",
      citation: "8-K: secured by substantially all assets of CoreWeave Compute Acquisition Co. VIII, LLC",
      noteZh: "SPV 資金注入基建（4.0 確實無追索）", noteEn: "Funds infrastructure (4.0 genuinely non-recourse)" },
    { source: "meta", target: "cw-spv8", type: "purchase", amount: 19,
      date: "2026", confidence: "reported",
      citation: "8-K: 單一「leading AI enterprise」合約為抵押核心；二手分析指認 Meta、~$19B backlog",
      noteZh: "單一客戶合約＝抵押品——投資級評級實質依賴 Meta 信用",
      noteEn: "Single-customer contract IS the collateral — IG rating leans on Meta's credit" },
    { source: "banks", target: "cw-spv5", type: "debt", amount: 3.1,
      date: "2026-05-15", confidence: "confirmed",
      citation: "CoreWeave 8-K (crwv-20260515): Ba2/BB+、SOFR+450、2031/11 到期、MS+MUFG 主辦；兩家客戶＝OpenAI + Cohere（Bloomberg 銀團報導 + PitchBook LCD, 2026-04/05；8-K 本身未具名）",
      noteZh: "DDTL 5.0：垃圾級、可二級交易；GPU 部署給 OpenAI 與 Cohere——OpenAI 在 CoreWeave 結構中第二度成為抵押信用",
      noteEn: "DDTL 5.0: junk, tradeable; GPUs deployed for OpenAI and Cohere — OpenAI appears as a collateral credit in CoreWeave's stack for the second time" },
    { source: "cw-spv5", target: "coreweave", type: "spv", amount: 3.1,
      date: "2026-05", confidence: "confirmed",
      citation: "8-K: 5.5 年期「對齊 GPU 部署時程與使用壽命」",
      noteZh: "把 6 年折舊假設直接寫進資本結構", noteEn: "Embeds the 6-yr depreciation assumption into the capital structure" },
    { source: "coreweave", target: "cw-spv5", type: "guarantee", amount: 3.1,
      date: "2026-05-15", confidence: "confirmed",
      citation: "8-K: 所有義務由 CoreWeave, Inc. 無條件擔保 + 100% 借款人股權質押",
      noteZh: "⚠ 母公司全額擔保——「破產隔離」是假象，SPV 違約直接回傷母公司",
      noteEn: "⚠ Full parent guarantee — 'bankruptcy-remote' is illusory; SPV default recourses straight back" },
    { source: "nvda", target: "coreweave", type: "equity", amount: 2,
      date: "2025", confidence: "reported",
      citation: "Senate FSOC letter: Nvidia 持 CoreWeave ~7%（金額按市值估）",
      noteZh: "晶片商持股自家客戶 ~7%", noteEn: "Chip vendor holds ~7% of its own customer" },
    { source: "nvda", target: "coreweave", type: "purchase", amount: 6.3,
      date: "2025-09", confidence: "confirmed",
      citation: "CoreWeave 8-K (2025-09-09): Nvidia 義務回購未售產能至 2032/04/13、訂單 $6.3B",
      noteZh: "Nvidia 回購未售算力（上限 $6.3B）——供應商為客戶需求背書",
      noteEn: "Nvidia backstops unsold capacity (capped $6.3B) — vendor guarantees customer demand" },
    { source: "coreweave", target: "openai", type: "equity", amount: 0.35,
      date: "2025-03", confidence: "confirmed",
      citation: "Senate letter: OpenAI 在算力協議中收到 $350M CoreWeave 股票",
      noteZh: "客戶的客戶收到客戶的股票——循環第三邊",
      noteEn: "The customer's customer paid in the customer's stock — third leg of the circle" },

    // ======== Meta / Hyperion 出表 ========
    { source: "blueowl", target: "beignet", type: "equity", amount: 2,
      date: "2025-10", confidence: "confirmed",
      citation: "Meta 一手新聞稿 (2025-10-21): Beignet Investor LLC、Blue Owl 80%/Meta 20%、股權合計 ~$2.5B",
      noteZh: "Blue Owl 持 JV 80%", noteEn: "Blue Owl holds 80%" },
    { source: "meta", target: "beignet", type: "equity", amount: 0.5,
      date: "2025-10", confidence: "confirmed",
      citation: "Meta 新聞稿: 20% 股權",
      noteZh: "Meta 出 20% 股權、保留營運控制與殘值擔保義務",
      noteEn: "Meta: 20% equity, keeps operational control and the RVG obligation" },
    { source: "pimco", target: "beignet", type: "debt", amount: 27.3,
      date: "2025-10", confidence: "confirmed",
      citation: "Senate letter + Bloomberg: ~$27.3B A+ 債、PIMCO 錨定 ~$18B、Morgan Stanley 主辦 (144A)",
      noteZh: "債券投資人實質持有 Meta 的資料中心", noteEn: "Bondholders effectively own Meta's data center" },
    { source: "beignet", target: "meta", type: "lease", amount: 27,
      date: "2025-10", confidence: "confirmed",
      citation: "Senate letter: Meta 售後回租 + 殘值擔保",
      noteZh: "售後回租——表外但風險未消失（BIS:『槓桿不會因為看不見而消失』）",
      noteEn: "Leaseback — off-B/S but risk persists (BIS: 'leverage does not disappear by being out of sight')" },
    { source: "meta", target: "beignet", type: "guarantee", amount: 28,
      date: "2025-10", confidence: "confirmed",
      citation: "Meta 10-Q Q1'26 權益法投資註記原文：RVG 門檻合計 ~$28B（隨時間遞減）、「付款不被認為可能、迄今未認列負債」；不併表 VIE、最大損失曝險 $45.99B",
      noteZh: "$28B 殘值擔保、零負債認列（10-Q 原文確認）；Meta 自揭最大曝險 $45.99B",
      noteEn: "$28B RVG, zero liability recorded (10-Q verbatim); Meta's own disclosed max exposure: $45.99B" },
    { source: "banks", target: "meta", type: "debt", amount: 30,
      date: "2025-10-30", confidence: "confirmed",
      citation: "Bloomberg: JV 公布數日後發 $30B 公司債（2025 美國投資級最大、$125B 認購簿）",
      noteZh: "出表的同時又上槓桿", noteEn: "Levering up on-B/S while moving assets off-B/S" },

    // ======== Stargate / Abilene ========
    { source: "openai", target: "stargate", type: "equity", amount: 19,
      date: "2025-01", confidence: "estimate",
      citation: "2025-01 宣布時廣泛報導之初始承諾；股權比例與實際部署未公開、本研究未能驗證",
      noteZh: "宣示性承諾（未驗證）", noteEn: "Announced commitment (unverified)" },
    { source: "softbank", target: "stargate", type: "equity", amount: 19,
      date: "2025-01", confidence: "estimate",
      citation: "同上；SoftBank 為主要出資方之一",
      noteZh: "宣示性承諾（未驗證）", noteEn: "Announced commitment (unverified)" },
    { source: "mgx", target: "stargate", type: "equity", amount: 7,
      date: "2025-01", confidence: "estimate",
      citation: "同上；MGX 確切支票額未公開",
      noteZh: "宣示性承諾（未驗證）", noteEn: "Announced commitment (unverified)" },
    { source: "blueowl", target: "abilene", type: "equity", amount: 15,
      date: "2025-05-21", confidence: "confirmed",
      citation: "Crusoe 一手新聞稿: Crusoe + Blue Owl Real Assets + Primary Digital $15B JV 二期（1.2GW、八棟、2026 年中通電；股權比例未揭露）",
      noteZh: "$15B JV 計畫總額（三方聯合, 比例未公開）", noteEn: "$15B JV program (three sponsors, splits undisclosed)" },
    { source: "banks", target: "abilene", type: "debt", amount: 9.6,
      date: "2025", confidence: "reported",
      citation: "CoStar via 深研: JPMorgan ~$9.6B 貸款（含 $7.1B 建設段）",
      noteZh: "JPMorgan 建設融資", noteEn: "JPMorgan construction financing" },
    { source: "abilene", target: "stargate", type: "lease", amount: 15,
      date: "2026", confidence: "reported",
      citation: "DCD/Epoch AI tracker: Abilene 為 Stargate 旗艦站、Oracle 營運供 OpenAI 使用；2026-03 約 600MW 擴建取消",
      noteZh: "旗艦站產能供給（3 月已現需求軟化訊號）",
      noteEn: "Flagship capacity (demand-softening signal in March)" },

    // ======== REIT / 電力 ========
    { source: "blackstone", target: "qts", type: "equity", amount: 10,
      date: "2021-08", confidence: "reported",
      citation: "Bisnow: Blackstone ~$10B 私有化 QTS，其後擴張 8 倍",
      noteZh: "PE 持有 + 重度證券化的資料中心平台", noteEn: "PE-owned, heavily securitized DC platform" },
    { source: "banks", target: "qts", type: "debt", amount: 5,
      date: "2025-07/11", confidence: "reported",
      citation: "Bisnow: $3.46B CMBS (2025-11, 10 座 DC) + $1.5B CMBS (2025-07)；DC ABS/CMBS H1'25 $13.4B、年增一倍、佔 SASB 13%",
      noteZh: "資料中心債務進入 CMBS 市場——傳染面再擴一層",
      noteEn: "DC debt enters CMBS — one more contagion surface" },
    { source: "amzn", target: "talen", type: "purchase", amount: 18,
      date: "2025-06-11", confidence: "confirmed",
      citation: "Talen 8-K (SEC): Susquehanna 1,920MW 供 AWS 至 2042（~$18B 為二手估計）；長約「顯著降低 Talen 市場風險」",
      noteZh: "核電 PPA——擱淺資產/需求風險由買方 Amazon 承擔",
      noteEn: "Nuclear PPA — stranded/demand risk borne by offtaker Amazon" },

    // ======== 終端曝險 ========
    { source: "pensions", target: "blueowl", type: "equity", amount: 7,
      date: "2025", confidence: "confirmed",
      citation: "Senate letter: NY+PA 州退休金投資 Blue Owl $7B 數位基建基金（LP 占比未揭露）",
      noteZh: "紐約州+賓州退休金 → Blue Owl 數位基建基金",
      noteEn: "NY+PA state pensions → Blue Owl digital infra fund" },
    { source: "pensions", target: "apollo", type: "equity", amount: 0,
      date: "2026", confidence: "confirmed",
      citation: "Fed via FSB (2026-05-06): 退休基金持有私募信貸基金 ~31% 資產（比例確認、AI 部分絕對額未拆分）",
      noteZh: "退休基金＝私募信貸最大 LP（~31%）；以比例呈現",
      noteEn: "Pensions = private credit's largest LP base (~31%); shown as share" },
    { source: "insurers", target: "apollo", type: "equity", amount: 0,
      date: "2026", confidence: "confirmed",
      citation: "FSB (2026-05): 壽險組合 ~10% 在私募信貸；保險資金直接參與 CW DDTL 4.0",
      noteZh: "壽險 ~10% 組合在私募信貸", noteEn: "~10% of life insurer portfolios in private credit" },
    { source: "banks", target: "apollo", type: "debt", amount: 220,
      date: "2026-05", confidence: "confirmed",
      citation: "FSB Report on Vulnerabilities in Private Credit (2026-05-06): 銀行對私募信貸基金授信 ~$220B（全行業，掛 Apollo 節點代表整層）",
      noteZh: "銀行 → 私募信貸授信 ~$220B（行業合計）",
      noteEn: "~$220B bank credit lines to private credit funds (industry-wide proxy)" },
  ],

  // ---- 資金循環：同一筆錢被計算幾次 / Capital circularity ----
  circularity: [
    {
      id: "cw-claim-stack",
      titleZh: "CoreWeave 索賠堆疊：一條客戶現金流上的 5-7 層權利",
      titleEn: "CoreWeave claim stack: 5-7 layers on one customer cash flow",
      multiplier: "5-7×",
      chain: ["msft", "coreweave", "cw-spv8", "banks", "pensions"],
      confidence: "confirmed",
      descZh: "同一條客戶合約現金流同時支撐：(1) SPV 資產質押 (2) 客戶合約質押 (3) SPV 股權質押 (4) 資料中心租約質押 (5) 母公司無條件擔保（DDTL 4.0 除外，為 bad-boy 擔保）(6) 計入 $98.8B RPO 支撐公司債與股權估值 (7) 同一義務出現（或表外掛著）在雲端巨頭自己帳上。Advance rate 可達 ~102% LTC——僅債務層就可超過資產成本。",
      descEn: "One contracted cash flow simultaneously supports: SPV asset pledge, contract pledge, SPV equity pledge, DC lease pledge, parent guarantee (all but 4.0), inclusion in $98.8B RPO backing corporate notes & equity, and the same obligation on the hyperscaler's own books. Advance rates to ~102% LTC — the debt layer alone can exceed asset cost.",
      citation: "CRWV 10-K FY2025 / 10-Q Q1'26 / DDTL 4.0 投資人簡報 (2026-03)；堆疊計數為對已驗證條款的分析推論",
    },
    {
      id: "nvda-triple-role",
      titleZh: "Nvidia 三重角色：供應商＋股東＋需求買回方",
      titleEn: "Nvidia's triple role: supplier + shareholder + demand backstop",
      multiplier: "3 角色",
      chain: ["nvda", "coreweave", "nvda"],
      confidence: "confirmed",
      descZh: "CoreWeave 8-K (2025-09-15) 原文確認：Nvidia 同時是 (a) GPU 供應商 (b) 股東 (c) 依 $6.3B 訂單義務回購 2032/4 前未售產能。供應商的銷售收入→變成客戶的資產→客戶拿資產抵押借錢→再買供應商的貨——而需求不足時由供應商自己接盤。",
      descEn: "CRWV 8-K confirms Nvidia is simultaneously (a) GPU supplier (b) stockholder (c) obligated buyer of unsold capacity through Apr 2032 ($6.3B order). Vendor revenue → customer asset → collateral for debt → more vendor purchases — with the vendor itself backstopping demand.",
      citation: "SEC 8-K crwv-20250909 Item 1.01（上限 $6.3B、可因違約/破產 30 日終止）",
    },
    {
      id: "amd-warrants",
      titleZh: "AMD 雙 penny warrant：客戶用「採購」換股權，間接採購也算",
      titleEn: "AMD's twin penny warrants: equity for purchases — indirect ones count",
      multiplier: "2 份",
      chain: ["amd", "openai", "amd"],
      confidence: "confirmed",
      descZh: "AMD Q1'26 10-Q：對 OpenAI（2025-10）與 Meta（2026-02）各發 160M 股 @ $0.01 權證，解鎖綁 Instinct GPU 採購里程碑——「含透過授權第三方間接採購」。意即經 Oracle/neocloud 中介的採購同樣解鎖股權：同一筆 GPU 訂單在中介商記營收、在 AMD 記營收、又解鎖客戶的 AMD 股權。截至 2026-03-28 尚無股份 vest。",
      descEn: "AMD 10-Q: 160M-share $0.01 warrants to both OpenAI (Oct-25) and Meta (Feb-26), vesting on Instinct purchase milestones 'including indirectly through authorized third parties' — one GPU order books revenue at the intermediary, revenue at AMD, and vests the customer's AMD equity. None vested as of Mar 28, 2026.",
      citation: "SEC 10-Q amd-20260328（權證列負債直到符合權益分類條件）",
    },
    {
      id: "msft-openai-loop",
      titleZh: "Microsoft–OpenAI 迴圈：投資變營收、虧損變權益法",
      titleEn: "Microsoft–OpenAI loop: investment becomes revenue, losses become equity-method",
      multiplier: "1$→2 帳",
      chain: ["msft", "openai", "msft"],
      confidence: "reported",
      descZh: "Microsoft 投資 ~$13B 取得 ~27%（$135B, 8-K）→ OpenAI 承諾回購 $250B Azure 服務 → 微軟一邊認列 Azure 營收、一邊按權益法吸收 OpenAI 虧損（列於其他收支）。同一段關係在微軟報表上同時是營收與虧損來源；具體權益法損失金額本研究未能從文件確認。",
      descEn: "Microsoft's ~$13B for ~27% → OpenAI's $250B Azure commitment → Microsoft books Azure revenue while absorbing equity-method losses in other income/expense. The exact loss line was not filing-confirmed this round.",
      citation: "Microsoft 8-K (msft-ex99_2)；權益法損失：deepquarry/calcbench 分析（reported 級）",
    },
    {
      id: "nvda-flywheel",
      titleZh: "Nvidia 飛輪：37% 營運現金流回灌客戶生態系、間接營收連三季自揭",
      titleEn: "Nvidia flywheel: 37% of OCF recycled into its customer ecosystem; indirect revenue self-disclosed three quarters running",
      multiplier: "37% OCF",
      chain: ["nvda", "openai", "coreweave", "nvda"],
      confidence: "confirmed",
      descZh: "全研究最強的 filing 級循環證據。Nvidia 10-K/10-Q 連續三份原文：「我們估計一家 AI 研究與部署公司（=OpenAI 的自我描述）透過向我們的客戶購買雲服務、間接貢獻了可觀的營收。」同期：單季 $18.6B 現金買私人 AI 股權（=當季 OCF 的 37%）、非上市投組 15 個月 $3.4B→$42.3B、另 $27B 已承諾；$15.9B 單季股權利得（含 CoreWeave/Intel 增值）灌入損益；前三大匿名客戶佔營收 54%、應收 64%。每一條腿文件都揭露了，只是從不把它們連成一個圈。",
      descEn: "The strongest filing-level circularity in this study. Three consecutive Nvidia filings state verbatim that 'one AI research and deployment company' (OpenAI's self-description) drives meaningful revenue indirectly through Nvidia's cloud customers — while Nvidia deploys $18.6B/quarter (37% of OCF) into private AI equity, books $15.9B/quarter of equity gains, and concentrates 54% of revenue in three unnamed customers. Every leg is disclosed; the circle is never drawn.",
      citation: "SEC 10-K nvda-20260125 + 10-Q nvda-20260426 + 10-Q nvda-20251026（OpenAI 指認為高度可信推論，文件未具名）",
    },
    {
      id: "amzn-mark-to-model",
      titleZh: "Amazon–Anthropic：投資→交付算力解鎖貸款→紙上增值入損益",
      titleEn: "Amazon–Anthropic: invest → compute delivery unlocks lending → paper gains to P&L",
      multiplier: "65% 營業利益",
      chain: ["amzn", "anthropic", "amzn"],
      confidence: "confirmed",
      descZh: "Amazon 10-Q 原文：$8B 可轉債 + $5B 特別股 + 至 $20B 融資額度——額度隨 Amazon「交付算力里程碑」解鎖。同時 Q1'26 認列 $15.6B 其他收益（$12.3B 為 Anthropic 特別股 Level 3 模型增值）≈ 當季營業利益的 65%。自己投資、自己供貨、自己放貸、自己估值、增值記進自己的獲利。",
      descEn: "Filing-verbatim: $8B notes + $5B preferred + up-to-$20B facility unlocking as Amazon hits compute-delivery milestones; meanwhile Q1'26 booked a $15.6B other-income gain ($12.3B Level 3 markup on Anthropic preferred) ≈ 65% of operating income. Invest, supply, lend, mark, and book the markup — all in-house.",
      citation: "SEC 10-Q amzn-20260331 Note 2（Level 3、未實現、可反轉；另 $4.1B 離散稅費）",
    },
    {
      id: "googl-equity-derivative",
      titleZh: "Alphabet：$40B 投資以「股權衍生品」入帳、對手不具名",
      titleEn: "Alphabet: a $40B investment booked as an 'equity derivative', counterparty unnamed",
      multiplier: "$1.1B→$40.7B",
      chain: ["googl", "anthropic", "anthropic-tpu-spv", "googl"],
      confidence: "confirmed",
      descZh: "Alphabet 10-Q：VIE 出資承諾一季從 $1.1B 跳到 $40.7B（$10B 資本承諾 + $30B 至 2030 里程碑出資、列為 Level 3 股權衍生品；對手未具名、與 Anthropic 一致）。同時 Google 把 TPU 賣給 Apollo/Blackstone SPV 收現、Anthropic 再用 Google 的錢付 TPU 租金。Alphabet 另揭露 $28.4B 資料中心信用衍生品 + $33.3B backstop 框架——也在變成第三方資料中心債的保險人。",
      descEn: "Alphabet's VIE commitments jumped $1.1B→$40.7B in one quarter ($10B + $30B milestone, booked as a Level 3 equity derivative, counterparty unnamed/Anthropic-consistent), while Google monetizes TPUs through the Apollo/Blackstone SPV and Anthropic pays TPU rent partly with Google's money. Alphabet also discloses $28.4B of DC credit derivatives + a $33.3B backstop framework — becoming an insurer of third-party data-center debt.",
      citation: "SEC 10-Q goog-20260331 VIE/衍生品註記",
    },
    {
      id: "softbank-margin-loop",
      titleZh: "SoftBank 自舉迴圈：用 OpenAI 股權借錢、再投 OpenAI",
      titleEn: "SoftBank bootstrap: borrow against the OpenAI stake to fund OpenAI",
      multiplier: "估值=抵押品",
      chain: ["openai", "softbank", "banks", "softbank", "openai"],
      confidence: "reported",
      descZh: "SoftBank 對 OpenAI 的 $64.6B 承諾，部分資金來自以 OpenAI 持股為抵押的 $10B 保證金貸款（SOFR+425）+ $40B 過橋。OpenAI 的一級市場估值（無日常定價）同時是 SoftBank 的資產、抵押品、與繼續出資的依據——估值漲，借款能力漲，再投入，估值再漲。反向亦然。",
      descEn: "Part of SoftBank's $64.6B OpenAI commitment is funded by a $10B margin loan collateralized by the OpenAI stake itself plus a $40B bridge. The (unmarked) private valuation is simultaneously SoftBank's asset, its collateral, and its capacity to keep investing — reflexive in both directions.",
      citation: "TNW (2026-04-23)；SoftBank 財報未直接驗證（東京上市、無 SEC 文件）",
    },
  ],

  contagionPaths: [
    {
      id: "coreweave-cascade",
      titleZh: "主路徑：CoreWeave 違約（FSB/BIS/參議院共同指認；母公司擔保使隔離失效）",
      titleEn: "Primary: CoreWeave default (flagged by FSB/BIS/Senate; parent guarantee defeats isolation)",
      trigger: "coreweave",
      steps: [
        { from: "openai", to: "coreweave", mechanismZh: "OpenAI 營收($13B) 撐不起承諾($1.4T) → 算力合約縮減/違約", mechanismEn: "OpenAI revenue ($13B) can't carry commitments ($1.4T) → contract cuts/defaults" },
        { from: "coreweave", to: "cw-spv5", mechanismZh: "SPV 抵押現金流中斷；GPU 租金市價已兩年跌 60-75%", mechanismEn: "SPV collateral cash flows break; GPU rentals already down 60-75% in 2 yrs" },
        { from: "cw-spv5", to: "coreweave", mechanismZh: "⚠ 母公司全額擔保 → 違約直接回傷 CoreWeave Inc. 全體債權人", mechanismEn: "⚠ Parent guarantee → default recourses to ALL CoreWeave Inc. creditors" },
        { from: "coreweave", to: "blackstone", mechanismZh: "私募信貸錨定投資人減記；可二級交易的 GPU 債價格崩跌放大訊號", mechanismEn: "Private credit anchors write down; tradeable GPU debt crashes, amplifying the signal" },
        { from: "blackstone", to: "insurers", mechanismZh: "保險組合（~10% 私募信貸）受損", mechanismEn: "Insurer portfolios (~10% private credit) hit" },
        { from: "blackstone", to: "pensions", mechanismZh: "退休基金 LP（~31% 私募信貸資產）淨值下修", mechanismEn: "Pension LPs (~31% of assets) marked down" },
        { from: "blackstone", to: "banks", mechanismZh: "銀行 ~$220B 授信被抽取/減值；CMBS 市場（DC 佔 SASB 13%）重定價", mechanismEn: "~$220B bank lines drawn/impaired; DC CMBS (13% of SASB) reprices" },
      ],
      severity: "high",
    },
    {
      id: "softbank-openai-channel",
      titleZh: "槓桿股權通道：SoftBank（OpenAI 估值的保證金貸款化）",
      titleEn: "Levered-equity channel: SoftBank (OpenAI's valuation, margin-loaned)",
      trigger: "softbank",
      steps: [
        { from: "openai", to: "softbank", mechanismZh: "OpenAI 估值($852B)下修 → $110B 持股縮水，而 $10B 保證金貸款的抵押品就是這筆持股", mechanismEn: "OpenAI valuation cut → $110B stake shrinks; the $10B margin loan is collateralized by that very stake" },
        { from: "softbank", to: "banks", mechanismZh: "追繳保證金 + $40B 過橋再融資困難；CDS 已 ~360bps、BB+ 負向", mechanismEn: "Margin calls + $40B bridge refi stress; CDS ~360bps, BB+ negative" },
        { from: "softbank", to: "stargate", mechanismZh: "Stargate 出資斷流 → 資料中心建設中斷（Abilene 已現取消訊號）", mechanismEn: "Stargate funding stalls → DC buildout halts (Abilene cancellation signal already visible)" },
      ],
      severity: "high",
    },
    {
      id: "anthropic-tpu-cascade",
      titleZh: "次路徑：Anthropic TPU SPV（Burry 的 $38B）",
      titleEn: "Secondary: Anthropic TPU SPV (Burry's $38B)",
      trigger: "anthropic",
      steps: [
        { from: "anthropic", to: "anthropic-tpu-spv", mechanismZh: "Anthropic 租金＝唯一主要還款來源；run-rate 有 gross/net 爭議(~$8B)", mechanismEn: "Anthropic rent = primary repayment source; run-rate has an ~$8B gross/net dispute" },
        { from: "anthropic-tpu-spv", to: "avgo", mechanismZh: "TPU 殘值擔保觸發 → Broadcom 承接 senior 尾部風險", mechanismEn: "RVG triggered → Broadcom absorbs senior tail risk" },
        { from: "anthropic-tpu-spv", to: "apollo", mechanismZh: "$4.5B B 段（無增強損失層）先歸零，再傷 A2", mechanismEn: "$4.5B B tranche zeroes first, then A2 impaired" },
        { from: "apollo", to: "insurers", mechanismZh: "Athene 式保險浮存金直接曝險", mechanismEn: "Athene-style insurance float directly exposed" },
      ],
      severity: "high",
    },
    {
      id: "cohere-price-discovery",
      titleZh: "資訊路徑：Cohere＝GPU 債的公開溫度計（金額無關、價格有關）",
      titleEn: "Information path: Cohere = the public thermometer of GPU debt (size-irrelevant, price-relevant)",
      trigger: "cohere",
      steps: [
        { from: "cohere", to: "cw-spv5", mechanismZh: "Cohere 成長放緩/違約 → 唯一可公開交易的 GPU 債（DDTL 5.0）價格下跌——金額 ~$1.5B 不重要，公開報價才重要", mechanismEn: "Cohere stumbles → the only publicly traded GPU debt reprices — the ~$1.5B is irrelevant, the public mark is everything" },
        { from: "cw-spv5", to: "blackstone", mechanismZh: "全市場第一個 public comp：$200B+ 不可交易 GPU 私募信貸被迫參照市價（FSB 的 stale-marks 問題終結）", mechanismEn: "First public comp: $200B+ of unmarked GPU private credit gets a reference price (ends FSB's stale-marks regime)" },
        { from: "blackstone", to: "coreweave", mechanismZh: "抵押品品質假設連鎖重審（RPO $98.8B → Oracle $553B → 102% LTC/折舊/殘值）→ CoreWeave 再融資窗口關閉——2026 到期 $6.1B vs 現金 $2.2B", mechanismEn: "Collateral-quality assumptions cascade (RPO → LTC → residuals) → CoreWeave's refi window shuts: $6.1B due 2026 vs $2.2B cash" },
        { from: "coreweave", to: "pensions", mechanismZh: "2007 ABX 先例：最小的違約 tranche + 公開指數 = 全體系被迫按市價計提", mechanismEn: "The 2007 ABX precedent: tiny defaulted tranches + a public index = system-wide forced marks" },
      ],
      severity: "medium",
    },
    {
      id: "oracle-channel",
      titleZh: "公開市場通道：Oracle（最大投資級傳導體）",
      titleEn: "Public-market channel: Oracle (largest IG transmission)",
      trigger: "orcl",
      steps: [
        { from: "openai", to: "orcl", mechanismZh: "$300B 合約若不實現，Oracle 債務（現金 4 倍）擱淺；CDS 已創 2009 來新高", mechanismEn: "If $300B doesn't materialize, Oracle's debt (4x cash) strands; CDS already at post-2009 high" },
        { from: "orcl", to: "banks", mechanismZh: "投資級債減值 → 公開債市、貨幣基金、401(k) 全面波及", mechanismEn: "IG bond impairment → public bond markets, MMFs, 401(k)s" },
      ],
      severity: "medium",
    },
  ],
};

if (typeof module !== "undefined") module.exports = DATA;
